### ISSUE TITLE
Project has to build only for x86

### ISSUE THREAD

**Issue by darrencomeau** [VulcanAnalytics/DBTester#45]
Because of issues with certain libraries the project has to be build as an x86 project.

This makes a barrier to entry as anyone trying to integrate the package has to go through and understand setting up a new solution/project build for `x86` instead of `Any CPU`.

SMO appears to get around this by explicitly including the libraries in the NuGet package.

**Comment by darrencomeau** [comment]
Was previously reviewed here...

https://github.com/VulcanAnalytics/DBTester/projects/1#card-13426296

**Comment by darrencomeau** [comment]
Can't replicate the failure yet.

Only receive the error;

> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "VulcanAnalytics.DBTester, Version=1.0.0.0, Culture=neutral, processorArchitecture=x86", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.

Will treat removing this error as the objective.

**Comment by darrencomeau** [comment]
Placing the `Any CPU` built dll in a local project doesn't cause an error but removes the message.

From memory, the issue was not ever faced on my local machine but for me when using an Azure DevOps build server.

Will turn on CI for the branch and make commits to see the break and fix.

**Comment by darrencomeau** [comment]
The unit tests fail now;

> 2018-10-29T04:46:25.6314010Z Error Message:
2018-10-29T04:46:25.6314523Z  Test method VulcanAnalytics.DBTester.dbSpecflow_tests.DatabaseTesterTests.InsertDataWikiExample threw exception: 
2018-10-29T04:46:25.6315349Z Microsoft.SqlServer.Management.Smo.FailedOperationException: ExecuteNonQuery failed for Database 'tempdb'.  ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.SqlServer.BatchParser, Version=14.100.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
2018-10-29T04:46:25.6315709Z Stack Trace:
2018-10-29T04:46:25.6316974Z     at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)
2018-10-29T04:46:25.6317508Z    at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
2018-10-29T04:46:25.6318387Z    at System.Reflection.Assembly.GetType(String name, Boolean throwOnError)
2018-10-29T04:46:25.6319111Z    at Microsoft.SqlServer.Management.Common.ServerConnection.GetStatements(String query, ExecutionTypes executionType, Int32& statementsToReverse)
2018-10-29T04:46:25.6320832Z    at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteNonQuery(String sqlCommand, ExecutionTypes executionType, Boolean retry)
2018-10-29T04:46:25.6321331Z    at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteNonQuery(StringCollection sqlCommands, ExecutionTypes executionType, Boolean retry)
2018-10-29T04:46:25.6321670Z    at Microsoft.SqlServer.Management.Smo.ExecutionManager.ExecuteNonQuery(StringCollection queries, ExecutionTypes executionType)
2018-10-29T04:46:25.6322240Z    at Microsoft.SqlServer.Management.Smo.Database.ExecuteNonQuery(StringCollection sqlCommands, ExecutionTypes executionType)
2018-10-29T04:46:25.6322401Z --- End of inner exception stack trace ---
2018-10-29T04:46:25.6322549Z     at Microsoft.SqlServer.Management.Smo.Database.ExecuteNonQuery(StringCollection sqlCommands, ExecutionTypes executionType)
2018-10-29T04:46:25.6322688Z    at Microsoft.SqlServer.Management.Smo.Database.ExecuteNonQuery(String sqlCommand, ExecutionTypes executionType)
2018-10-29T04:46:25.6322832Z    at Microsoft.SqlServer.Management.Smo.Database.ExecuteNonQuery(String sqlCommand)
2018-10-29T04:46:25.6323004Z    at VulcanAnalytics.DBTester.MsSqlDatabaseTester.ExecuteStatementWithoutResult(String sqlStatement) in D:\a\1\s\src\DatabaseTester_net40\MsSqlDatabaseTester.cs:line 112
2018-10-29T04:46:25.6323167Z    at VulcanAnalytics.DBTester.dbSpecflow_tests.DatabaseTesterTests.InsertDataWikiExample() in D:\a\1\s\tests\DatabaseTester_net40_Tests\DatabaseTesterTests.cs:line 100

**Comment by darrencomeau** [comment]
This issue doesn't appear to be present in Visual Studio 2019
